flake.lock, flake.nix, lib/default.nix
This replaces digga, which is bulky and contains a lot of unnecessary dependencies, with flake-utils, which is a single dependency that maintains the normal flake construction process. (As opposed to a wrapper like `mkFlake`.)
Resolves #3 
Additionally, this replaces the overlay's hardcoded `x86-64_linux` with a reference to the host's system, making the overlay cross-platform.
=> refactor(flake): replace digga with flake-utils

modules/minecraft-servers.nix
Use `lib.getExe` instead of assuming the executable is named `minecraft-server`.
=> module: getExe instead of /bin/minecraft-server

.github/workflows/update-locks.yml
Automate running the `update.py` scripts and committing the results. An example of a commit it creates: https://github.com/Misterio77/nix-minecraft/commit/b97a92e39228917aa19620a1897e8e3958be83b1
=> add github action for auto updates

modules/minecraft-servers.nix
If the parent directory doesn't exist `ln` will fail, so i `mkdir -p` the parent. My usecase was 
```nix
{
services.minecraft-servers = {
enable = true;
eula = true;
servers = {
"test" = {
enable = true;
openFirewall = true;
package = mcPkgs.paperServers.paper-1_19_3;
symlinks = {
mods = pkgs.linkFarmFromDrvs "mods" (map mcPkgs.fetchModrinthMod (builtins.attrValues {
UnifiedMetrics = {
id = "YREl7q0o";
hash = "sha256-3/MjbjBI+FkDOiTeHftZuARGIrgexXdAPsrcTfLFih8=";
};
}));
"config/unifiedmetrics/config.yml" = pkgs.writeText "unifiedmetrics-config.yml" (builtins.toJSON {
server.name = "global";
metrics = {
enabled = true;
driver = "prometheus";
collectors = {
systemGc = true;
systemMemory = true;
systemProcess = true;
systemThread = true;
server = true;
world = true;
tick = true;
events = …
```
=> fix: create parent directories for symlinks with nested paths

modules/minecraft-servers.nix
Fixes #14
For some reason I just didn't read that RuntimeDirectory was explicitly cleared by systemd with the service stops/restarts.
This led to all of the other tmux sockets becoming lost whenever a server restarted or was stopped.
=> fix(minecraft-servers): don't clear runtime dir

pkgs/fabric-servers/loader.nix, pkgs/helpers/fetchModrinthMod.nix, pkgs/legacy-fabric-servers/loader.nix, pkgs/minecraft-servers/derivation.nix, pkgs/paper-servers/derivation.nix, pkgs/quilt-servers/loader.nix, pkgs/velocity-servers/derivation.nix
Now that I think of it it's actually weird for nixpkgs to include a C compiler by default instead of the other way round :thinking: 
Anyway, here's the PR
=> fix: replace stdenv with stdenvNoCC to remove gcc dependency

modules/minecraft-servers.nix
Hello!
First of all, thanks a lot for this awesome module!
I've been trying to get a full minecraft server network going, and it's been going great! I've made a couple of changes for my own use, so here's one of them, in case you're interested.
The ideia is that a lot of configuration files (specially plugins) behave terribly when faced with the read-only fs link destinations. Paper, for example, completely crashes if `config/paper.yml` is read-only.
A solution I've come up with is adding a `files` option that behaves similarly to `symlinks`, but it dereferences the file, making it mutable. That way, the plugin/mod/server can behave as expected, while keeping reproducibility (as the files are copied again each time the service starts).
An existing file with the same name is only backed up …
=> Option for copying files (instead of symlinking)

modules/minecraft-servers.nix
The commands would fail when the file names contain a `'`
=> module: fix command filename quoting

flake.nix, tests/files-symlinks.nix, tests/simple.nix
Hi! This is me again, with the first of 4 PRs this time xD
This PR adds simple NixOS integration tests, which can be run with `nix flake check` (or individually with `nix build .#checks.x86_64-linux.simple`).
For now, there's two:
- Simple: runs the vanilla server and check that it actually started
- Files & Symlinks: runs the paper server, with two nix expression-generated files (ops.json and paper.yml), as well as symlink (a vanilla jar that is nescessary to avoid paper trying to download it at runtime).
- In a follow-up PR (will open it in a few minutes), I will use this to test command execution:
- I de-op `Misterio7x`, this mutates the ops.json, so validates that `files` are mutable.
- I run a unknown command and grep the output, validating that the `paper.yml` `unknown-command` is …
=> tests: init

modules/minecraft-servers.nix
This PR hardens the minecraft service, and in that process uses systemd to create directories (and set permissions), instead of relying on scripts.
Try running `systemd-analyze security`, and you'll see that the current score is < 1. With this PR, it increases to 3.
I also changed the umask from `002` to `007`, this means new files will be `770` and not `775`. I think this is better, as other users (that are not in the group) should not have any access to the files whatsoever.
=> Harden module, use systemd.tmpfiles to create dirs

modules/minecraft-servers.nix
This PR makes it possible to have Nix reload the service instead of restarting it, when it's changed.
This is very useful for servers you don't want to take down when switching; you can also add custom commands to run on reload (e.g. issuing a command through tmux to reload a specific plugin)
=> module: add enableReload

pkgs/velocity-servers/default.nix
stablePackages previously filtered the experimental builds, but did not account for a possibility where every single build within a version was experimental (the empty list would be kept, thus breaking `last`).
This just happened now with 3.3.0 (where every single build is currently experimental).
```
$ nix build github:infinidoge/nix-minecraft#velocity-server
error:
… while evaluating the attribute 'velocity-server'
at /nix/store/63yr5rbdg9wkzbzrz7ww29pyzil33hk2-source/flake.nix:41:11:
40|           paper-server = paperServers.paper;
41|           velocity-server = velocityServers.velocity;
|           ^
42|           minecraft-server = vanilla-server;
… while evaluating the attribute 'velocity'
at /nix/store/35dcag44a0ymww0vy0s4jjgxwpv9g62d-source/lib/attrsets.nix:488:14:
487| …
```
=> velocity: fix latest

modules/minecraft-servers.nix
This assertion triggers when `minecraft-server` is not enabled and the `dataDir`s are equal. I'm assuming this is a bug, and the `!` was meant to negate the whole expression (and also swapping the `!=` for an `==`), but I think the implication arrow makes the intent more clear.
=> module: fix assertion for clashing `dataDir`s

pkgs/velocity-servers/derivation.nix
Removes the warning when using the velocity-server derivation with the nixos module:
```
trace: warning: getExe: Package "velocity-3.3.0-SNAPSHOT-build.316" does not have the meta.mainProgram attribute.
We'll assume that the main program has the same name for now, but this behavior is deprecated, because it leads to surprising errors when the assumption does not hold.
If the package has a main program, please set `meta.mainProgram` in its definition to make this warning go away.
Otherwise, if the package does not have a main program, or if you don't control its definition, use getExe' to specify the name to the program, such as lib.getExe' foo "bar".
```
=> Add mainProgram to velocity-server derivation

modules/minecraft-servers.nix
Previously, `cfg.user` and `cfg.group` were not used by the systemd service. This commit fixes this and also disables creation of the `minecraft` user and group if the user and group are changed.
=> module: use user and group from configuration

pkgs/build-support/mkTextileLoader.nix
Added the small workaround to extract the asm version from list of libaries to the [mkTextileLoader.nix](https://github.com/mechan1sm/nix-minecraft/blob/master/pkgs/build-support/mkTextileLoader.nix#L19).
The list of libraries must contain exactly one string matching the following regular expression:
```nix
"org\\.ow2\\.asm:asm:([\.0-9]+)"
```
This should fix those errors for fabric/legacy-fabric/quilt servers, cause they are only ones using mkTextileLoader.
Related to issues #79 and #83, and pull request #80
=> textile-servers: dynamically set jar asm version

.vscode/settings.json, CHANGELOG.md, flake.nix, modules/minecraft-servers.nix, tests/files-symlinks.nix, tests/simple-systemd-socket.nix
Supersedes #52. Partially fixes #63 (per-server user & group configuration missing).
This PR adds a way to make servers managed via a systemd stdin socket and the journal, allowing for a better integrated experience with the rest of the system.
This PR largely builds on top of @Misterio77's excellent #52 and retains the nice additions:
* expanded tests verifying automated command execution
* extra lifecycle hooks for the server services
I did change the default systemd socket path from #52 to be aligned with the current tmux socket path and renamed the lifecycle hooks to preserve the systemd naming convention, though.
I've added a few extras, not all of which I'm sure want to be kept. Feedback welcome. :slightly_smiling_face:
* `docsAsciiDoc` and `docsCommonMark` package outputs (not …
=>  module: allow management via systemd socket

modules/minecraft-servers.nix
Adds a new option, `servers.<name>.operators`, to generate `ops.json`, similarly to `whitelist.json`.
It redefines `minecraftUUID` which doesn't feel very good, but to be completely honest I'm pretty new to nix and don't know where a wider-scoped definition would fit better
=> module: add operators

README.md
Some server jar files are either too niche to be merged into the project, or make my head spin on even attempting to get officially merged with the Python scripting involved to do so. However, I've found it's very easy to override the src of the vanilla server's package to support custom jar files. My small contribution is documenting how to do so and letting people know it's possible :)
=> meta: document overriding custom server jar

modules/minecraft-servers.nix, tests/files-symlinks.nix
Hi there! I was still bothered by the fact that symlinks/files aren't cleaned up when removed from the config (and stopWhenChanged prevents us from using stuff such as reload), so I decided to try a different approach.
The new system works by adding a file (.nix-minecraft-managed) to track managed files and symlinks. This makes it possible to correctly cleanup managed files (when stopping, restarting, reloading).
I've also added support for directories (https://github.com/Infinidoge/nix-minecraft/issues/73), and ensured only non-binary files are substituted with env vars (https://github.com/Infinidoge/nix-minecraft/issues/70)
Marked as draft as I'm still testing it.
Fixes #73
Fixes #70
=> refactor file & symlink

README.md, lib/default.nix
This is a lib function that recursively reads a directory, and returns them in the format expected by `files`/`symlinks`. This makes it possible to, for example, link all mods from a modpack, and still include additional mods.
=> lib: add collectFiles and collectFilesAt

pkgs/tools/fetchPackwizModpack/default.nix, tests/packwiz-from-src/default.nix, tests/packwiz-from-src/sample-pack/index.toml, tests/packwiz-from-src/sample-pack/mods/lithium.pw.toml, tests/packwiz-from-src/sample-pack/pack.toml
Allows for setting an src argument for the `fetchPackwizModpack` function. It needs to be a derivation or a file path containing a `pack.toml` file.
I'm using `updog` to serve the contents of `src` to `packwizInstallerBootstrap` rather than `packwiz serve`, since the latter would attempt to update the contents of the working directory on top of just serving the files, which does not work for read only nix store file paths.
I've been using the code [for myself](https://github.com/ehllie/vanilla-plus/blob/main/bootstrapPackwiz.nix) for a while now, and figured I'd try to upstream that change.
Should close #110.
=> Make fetchPackwizModpack work with an `src` argument

modules/minecraft-servers.nix
This pull request clears any input in the tmux session before sending the stop command, preventing stop failures if leftover text is present.
=> Clear input in tmux session before sending stop command
